name: probe4
on:
  workflow_dispatch:
    inputs:
      hostname:
        description: 'x'
        required: false
        default: ''
run-name: 'probe4 ${{ inputs.hostname || github.run_id }}'
jobs:
  p:
    runs-on: macos-latest
    steps:
      - run: echo ok