name: probe3
on:
  workflow_dispatch:
    inputs:
      hostname:
        description: 'x'
        required: false
        default: ''
run-name: 'probe3 ${{ inputs.hostname }}'
jobs:
  p:
    runs-on: macos-latest
    steps:
      - run: echo ok