name: probe2
on:
  workflow_dispatch:
    inputs:
      hostname:
        description: 'x'
        required: false
        default: ''
run-name: 'probe2 ${{ github.run_id }}'
defaults:
  run:
    shell: bash
    working-directory: ${{ github.workspace }}
jobs:
  p:
    runs-on: macos-latest
    steps:
      - run: echo ok